services:
  frontend:
    build:
      target: stage
      context: .
    image: chess-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    network_mode: npm_default
    container_name: chess-app