services:
  frontend:
    build:
      target: stage
      context: .
    image: chess-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    container_name: chess-app
    networks:
      - npm_default
  
networks:
  npm_default:
    driver: bridge